//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class family
    {
        public Nullable<int> idperson { get; set; }
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    
        public virtual person person { get; set; }
    }
}
